name: test-github-actions-services

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: root
      REDIS_ADDR: http://localhost:6370

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

          # Set health checks to wait until redis has started
        options: >-
          --entrypoint redis-server
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      vault:
        image: hashicorp/vault:latest
        ports:
          - 8200:8200
        options: >-
          --cap-add=IPC_LOCK
          --env VAULT_DEV_ROOT_TOKEN_ID=root
          --env VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
          --entrypoint /bin/sh -c "vault server -dev"

    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"

      - name: Setup Go
        uses: "actions/setup-go@v5"

      - name: Compile Code
        run: |
          go mod download
          go mod tidy
          go run main.go
