name: test-github-actions-services

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

          # Set health checks to wait until redis has started
        options: >-
          --entrypoint redis-server
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    #   vault:
    #     image: hashicorp/vault:latest
    #     ports:
    #       - 8200:8200
    #     options: >
    #       ""

    # env:
    #   REDIS_HOST: redis
    #   REDIS_PORT: ${{ github.job.services.redis.ports[6379] }}

    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"

      - name: Setup Go
        uses: "actions/setup-go@v5"

      - name: Complite Code
        run: |
          go mod download
          go mod tidy
          go run main.go
